apiVersion: v1
kind: ConfigMap
metadata:
  name: togglemaster-config
  namespace: togglemaster
data:
  AWS_REGION: "us-east-1"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/523694734848/toggle-master"

  AUTH_SERVICE_URL: "http://auth-service:8001"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  EVALUATION_SERVICE_URL: "http://evaluation-service:8004"
  ANALYTICS_SERVICE_URL: "http://analytics-service:8005"

  AUTH_DB_HOST: "togglemaster-auth-db.ccr0ewmoayb5.us-east-1.rds.amazonaws.com"
  AUTH_DB_NAME: "auth_db"
  AUTH_DB_PORT: "5432"

  FLAG_DB_HOST: "togglemaster-flag-db.ccr0ewmoayb5.us-east-1.rds.amazonaws.com"
  FLAG_DB_NAME: "flags_db"
  FLAG_DB_PORT: "5432"

  TARGETING_DB_HOST: "togglemaster-targeting-db.ccr0ewmoayb5.us-east-1.rds.amazonaws.com"
  TARGETING_DB_NAME: "targeting_db"
  TARGETING_DB_PORT: "5432"

  REDIS_HOST: "master.togglemaster-redis.h0xjab.use1.cache.amazonaws.com"
  REDIS_PORT: "6379"
