apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- observability/namespace.yaml
- configmap.yaml
- apps/auth-service/deployment.yaml
- apps/flag-service/deployment.yaml
- apps/targeting-service/deployment.yaml
- apps/evaluation-service/deployment.yaml
- apps/analytics-service/deployment.yaml
- ingress.yaml
- evaluation-ingress.yaml

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 91.9.0
  releaseName: prometheus
  namespace: observability
  valuesFile: observability/prometheus/values.yaml
