# Exemplo apenas para documentação.
# NÃO aplicar este arquivo em produção.
# Os Secrets reais são gerenciados fora do GitOps.

apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-db
  namespace: togglemaster
type: Opaque
stringData:
  AUTH_DATABASE_URL: "postgres://togglemaster:CHANGE_ME@AUTH_RDS_ENDPOINT:5432/auth_db?sslmode=require"
  FLAG_DATABASE_URL: "postgres://togglemaster:CHANGE_ME@FLAG_RDS_ENDPOINT:5432/flags_db?sslmode=require"
  TARGETING_DATABASE_URL: "postgres://togglemaster:CHANGE_ME@TARGETING_RDS_ENDPOINT:5432/targeting_db?sslmode=require"

---
apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-auth
  namespace: togglemaster
type: Opaque
stringData:
  MASTER_KEY: "CHANGE_ME"

---
apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-service-api
  namespace: togglemaster
type: Opaque
stringData:
  SERVICE_API_KEY: "CHANGE_ME"
